# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish (CI)

on:
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"

env:
  DOTNET_CONFIGURATION: Release

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src

      - name: Build ${{ env.DOTNET_CONFIGURATION }} packages
        run: dotnet build --no-restore -c ${{ env.DOTNET_CONFIGURATION }}
        working-directory: src

      - name: Publish NuGet package CSnakes.Runtime
        run: dotnet pack --no-build -c ${{ env.DOTNET_CONFIGURATION }} -o ../nuget -p:VersionSuffix='alpha.${{ github.run_number }}'
        working-directory: src

      - name: Publish NuGet packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./nuget
